import Server.Server;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Server server = new Server();
        server.start();
    }
}
